apiVersion: apps/v1
kind: Deployment
metadata:  #元数据
  name: nginx-deployment
  labels:
    app: nginx
spec:  #设置
  replicas: 2  #设置2个nginx服务
  selector:
    matchLabels:
      app: nginx
  template:  #配置
    metadata:
      labels:
        app: nginx
    spec:
      containers:  #去docker下载nginx
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        env:
          -name: ADDR
          value: :8080
        resources:  #给你的资源
          limits:
            cpu: 100m
            memory: 128Mi