# 启动编译环境
FROM golang:1.17 AS builder

# 配置编译环境
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.cn,direct

# 拷贝源代码到镜像
COPY . /go/src/coolcar/server

# 编译
WORKDIR /go/src/coolcar/server
RUN CGO_ENABLED=0 GOOS=linux go install ./gateway/...

# 生产镜像  docker 多阶段编译
FROM alpine:3.13
COPY --from=builder /go/bin/gateway /bin/gateway

# 暴露端口
EXPOSE 8080

# 设置服务入口
ENTRYPOINT [ "/go/bin/gateway" ]